name: Build, Package, and Release

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Adjust the Java version as needed

    - name: Build with Gradle and Shade Dependencies
      run: |
        ./gradlew clean build shadowJar  # Replace with your Gradle build commands

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar  # Path to the shaded JAR file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub

    - name: Get Release ID
      id: get_release_id
      run: echo "Release ID is ${{ steps.create_release.outputs.id }}"
